//=============================================================================
// Phear (phear@utassault.net)
//=============================================================================
class LeagueAS_ServerListWindow expands UTBrowserServerListWindow;

defaultproperties
{
      ServerListTitle="League Assault"
      ListFactories(0)="LeagueAS.LeagueAS_Browser"
      PingingText="Pinging League Assault Servers"
}
